# Loads Bosch Heatpump Raw Data and aggregates the heatpumps

## Calling relevant libraries ##

In [15]:
import json
import pandas as pd
import numpy as np

import pandas as pd
from retry_requests import retry
import os

# Extract weather data csvs for each PLZ and combine #

In [55]:
path = 'weather/'

list_files_31 = [fn for fn in os.listdir(path) if fn.startswith('31_')]
list_files_31.sort()
list_files_31

['31_20231112.csv', '31_20240101.csv', '31_20240328.csv', '31_20240501.csv']

In [56]:
path = 'weather/'


#list_names = ['64_20230925', '64_20231000', '38_20240112', '38_20240202', '38_20240404', '38_20240423']
 
# create empty dataframe
df_31 = pd.DataFrame()
 
# append datasets into the list


df_31['plz_2d'] = '31'
df_31

,date,temp_dc_max,temp_dc_min,temp_dc_mean,precipitation_sum_mm,rain_sum_mm,snowfall_sum_cm,precipitation_hours,wind_speed_kmh_max,shortwave_radiation_mj_sum,et0_fao_evapotranspiration_mm,relative_humidity_%,dew_point_dc,pressure_sea_hpa,surface_pressure_hpa,plz_2d
0,2023-11-20 00:00:00+00:00,10.692666,6.709333,9.535027,8.366666,8.366666,0.000000,15.333333,26.727896,1.426667,0.380454,90.979930,8.126695,1007.00977,997.89230,31
1,2023-11-21 00:00:00+00:00,7.592667,3.392667,6.184333,1.933333,1.933333,0.000000,9.000000,14.722599,1.220000,0.272542,91.924340,4.945445,1016.07635,1006.76710,31
2,2023-11-22 00:00:00+00:00,3.142667,-1.207333,1.170445,0.000000,0.000000,0.000000,0.000000,19.981714,3.296667,0.484117,82.839000,-1.564972,1028.39720,1018.80270,31
3,2023-11-23 00:00:00+00:00,10.592667,3.826000,8.347527,4.300000,4.300000,0.000000,12.000000,33.964140,0.983333,0.629582,85.837290,6.058639,1015.54443,1006.30880,31
4,2023-11-24 00:00:00+00:00,8.426000,2.042667,4.450306,7.566667,4.900000,1.866667,18.666666,27.841127,3.093333,0.559272,85.991200,2.303083,1004.43060,995.17120,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,2024-06-07 00:00:00+00:00,18.809334,8.659333,14.354472,0.033333,0.033333,0.000000,0.333333,14.747330,21.003334,3.726972,64.456696,7.045445,1017.80000,1008.73773,31
38,2024-06-08 00:00:00+00:00,21.892664,8.592667,15.929471,0.000000,0.000000,0.000000,0.000000,23.142403,24.580002,4.686554,62.643290,8.151694,1011.80835,1002.84890,31
39,2024-06-09 00:00:00+00:00,18.526000,9.342667,14.134334,0.000000,0.000000,0.000000,0.000000,19.968811,23.696665,4.161419,62.702988,6.362806,1009.53060,1000.53735,31
40,2024-06-10 00:00:00+00:00,15.159333,8.776000,12.156555,6.233333,6.233333,0.000000,10.000000,20.070208,10.416667,1.905433,77.272610,8.163501,1006.36670,997.34010,31
41,2024-06-11 00:00:00+00:00,15.676000,9.326000,12.021832,2.833333,2.833333,0.000000,15.333333,28.521929,23.250000,3.487767,72.364235,6.905861,1011.14720,1002.07227,31

In [42]:
print(df_38.dtypes)

date                              object
temp_dc_max                      float64
temp_dc_min                      float64
temp_dc_mean                     float64
precipitation_sum_mm             float64
rain_sum_mm                      float64
snowfall_sum_cm                  float64
precipitation_hours              float64
wind_speed_kmh_max               float64
shortwave_radiation_mj_sum       float64
et0_fao_evapotranspiration_mm    float64
relative_humidity_%              float64
dew_point_dc                     float64
pressure_sea_hpa                 float64
surface_pressure_hpa             float64
plz_2d                            object
dtype: object

In [57]:
# df_38['date'] = df_38['date'].dt.date
df_31['date'] = pd.to_datetime(df_31['date'])
print(df_31.dtypes)

date                             datetime64[ns, UTC]
temp_dc_max                                  float64
temp_dc_min                                  float64
temp_dc_mean                                 float64
precipitation_sum_mm                         float64
rain_sum_mm                                  float64
snowfall_sum_cm                              float64
precipitation_hours                          float64
wind_speed_kmh_max                           float64
shortwave_radiation_mj_sum                   float64
et0_fao_evapotranspiration_mm                float64
relative_humidity_%                          float64
dew_point_dc                                 float64
pressure_sea_hpa                             float64
surface_pressure_hpa                         float64
plz_2d                                        object
dtype: object

In [58]:
df_31.to_csv('weather/31_all.csv', index=False)